# Generated by Django 4.2.19 on 2026-08-21 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('api_key_hash', models.CharField(max_length=255)),
                ('api_key_prefix', models.CharField(default='hms_', max_length=12)),
                ('is_active', models.BooleanField(default=True)),
                ('allowed_ip_addresses', models.JSONField(blank=True, default=list)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('source_system', models.CharField(blank=True, max_length=120)),
                ('destination_system', models.CharField(blank=True, max_length=120)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], default='inbound', max_length=20)),
                ('message_type', models.CharField(default='unknown', max_length=50)),
                ('protocol', models.CharField(choices=[('fhir', 'FHIR'), ('hl7', 'HL7')], default='fhir', max_length=20)),
                ('resource_type', models.CharField(blank=True, max_length=50)),
                ('correlation_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('queued', 'Queued'), ('failed', 'Failed')], default='accepted', max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('raw_payload', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='integration.integrationclient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
