# Generated by Django 4.2.19 on 2026-08-07 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        ('integration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationmessage',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='integration_messages', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='integrationclient',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='integration_clients', to='tenants.tenant'),
        ),
    ]
