# Generated by Django 4.2.19 on 2026-08-07 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('subjective', models.TextField(blank=True)),
                ('objective', models.TextField(blank=True)),
                ('assessment', models.TextField(blank=True)),
                ('diagnosis_codes', models.JSONField(blank=True, default=list)),
                ('differential_diagnosis', models.TextField(blank=True)),
                ('plan', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_final', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Consultation Note',
                'verbose_name_plural': 'Consultation Notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EarlyWarningScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('respiration_score', models.IntegerField(default=0)),
                ('oxygen_score', models.IntegerField(default=0)),
                ('temperature_score', models.IntegerField(default=0)),
                ('systolic_bp_score', models.IntegerField(default=0)),
                ('heart_rate_score', models.IntegerField(default=0)),
                ('consciousness_score', models.IntegerField(default=0)),
                ('total_score', models.IntegerField(default=0)),
                ('risk_level', models.CharField(choices=[('low', 'Low (0-4)'), ('medium', 'Medium (5-6)'), ('high', 'High (7+)')], default='low', max_length=20)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Early Warning Score',
                'verbose_name_plural': 'Early Warning Scores',
                'ordering': ['-calculated_at'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('drug_name', models.CharField(max_length=200)),
                ('dosage', models.CharField(max_length=100)),
                ('frequency', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('route', models.CharField(choices=[('oral', 'Oral'), ('iv', 'IV'), ('im', 'IM'), ('sc', 'SC'), ('topical', 'Topical'), ('inhalation', 'Inhalation'), ('rectal', 'Rectal'), ('vaginal', 'Vaginal'), ('otic', 'Otic'), ('ophthalmic', 'Ophthalmic')], default='oral', max_length=50)),
                ('instructions', models.TextField(blank=True)),
                ('special_instructions', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('prescribed', 'Prescribed'), ('dispensed', 'Dispensed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='prescribed', max_length=20)),
                ('prescribed_date', models.DateTimeField(auto_now_add=True)),
                ('dispensed_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Prescription',
                'verbose_name_plural': 'Prescriptions',
                'ordering': ['-prescribed_date'],
            },
        ),
        migrations.CreateModel(
            name='VitalSign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('pulse', models.IntegerField(blank=True, null=True)),
                ('respiratory_rate', models.IntegerField(blank=True, null=True)),
                ('blood_pressure_systolic', models.IntegerField(blank=True, null=True)),
                ('blood_pressure_diastolic', models.IntegerField(blank=True, null=True)),
                ('oxygen_saturation', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('bmi', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('pain_score', models.IntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2 - Mild'), (3, '3'), (4, '4 - Moderate'), (5, '5'), (6, '6'), (7, '7 - Severe'), (8, '8'), (9, '9'), (10, '10 - Worst')], null=True)),
                ('consciousness', models.CharField(blank=True, choices=[('Alert', 'Alert'), ('Voice', 'Responds to Voice'), ('Pain', 'Responds to Pain'), ('Unresponsive', 'Unresponsive')], default='Alert', max_length=20)),
                ('blood_glucose', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Vital Sign',
                'verbose_name_plural': 'Vital Signs',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='VitalSignAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('alert_type', models.CharField(choices=[('early_warning', 'Early Warning Score'), ('bp_abnormal', 'Blood Pressure Abnormal'), ('fever', 'Fever / Temperature Abnormal'), ('tachycardia', 'Heart Rate Abnormal'), ('bradycardia', 'Heart Rate Abnormal'), ('tachypnoea', 'Respiratory Rate Abnormal'), ('hypoxia', 'Oxygen Saturation Low'), ('critical', 'Critical Alert'), ('custom', 'Custom Alert')], max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('notification_sent', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Vital Sign Alert',
                'verbose_name_plural': 'Vital Sign Alerts',
                'ordering': ['-created_at'],
            },
        ),
    ]
