# Generated by Django 4.2.7 on 2026-01-30 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        ('clinical', '0002_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitalsign',
            name='recorded_by',
            field=models.ForeignKey(limit_choices_to={'role__in': ['nurse', 'doctor']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.tenantuser'),
        ),
        migrations.AddField(
            model_name='vitalsign',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vital_signs', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='vitalsign',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vital_sign_records', to='patients.patientvisit'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='dispensed_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'pharmacist'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispensed_prescriptions', to='tenants.tenantuser'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='prescribed_by',
            field=models.ForeignKey(limit_choices_to={'role': 'doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.tenantuser'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='patients.patientvisit'),
        ),
        migrations.AddField(
            model_name='consultationnote',
            name='doctor',
            field=models.ForeignKey(limit_choices_to={'role': 'doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.tenantuser'),
        ),
        migrations.AddField(
            model_name='consultationnote',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_notes', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='consultationnote',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_notes', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='consultationnote',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_notes', to='patients.patientvisit'),
        ),
    ]
