# Generated by Django 4.2.19 on 2026-08-14 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationnote',
            name='admission_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consultationnote',
            name='billing_items',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='consultationnote',
            name='chief_complaint',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consultationnote',
            name='disposition_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consultationnote',
            name='disposition_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='consultationnote',
            name='family_history',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='consultationnote',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultationnote',
            name='follow_up_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consultationnote',
            name='follow_up_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultationnote',
            name='history_of_present_illness',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consultationnote',
            name='ice_concerns',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consultationnote',
            name='ice_expectations',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consultationnote',
            name='ice_ideas',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consultationnote',
            name='insurance_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='consultationnote',
            name='insurance_covered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consultationnote',
            name='is_signed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consultationnote',
            name='past_medical_history',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='consultationnote',
            name='physical_exam',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='consultationnote',
            name='signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultationnote',
            name='social_history',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddIndex(
            model_name='consultationnote',
            index=models.Index(fields=['tenant', 'visit', '-created_at'], name='clinical_co_tenant__ca5f97_idx'),
        ),
    ]
