# Generated by Django 4.2.7 on 2026-06-29 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_bulkpatientupload'),
        ('tenants', '0002_tenantuser_profile_picture'),
        ('clinical', '0003_alter_prescription_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='EarlyWarningScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('respiration_score', models.IntegerField(default=0)),
                ('oxygen_score', models.IntegerField(default=0)),
                ('temperature_score', models.IntegerField(default=0)),
                ('systolic_bp_score', models.IntegerField(default=0)),
                ('heart_rate_score', models.IntegerField(default=0)),
                ('consciousness_score', models.IntegerField(default=0)),
                ('total_score', models.IntegerField(default=0)),
                ('risk_level', models.CharField(choices=[('low', 'Low (0-4)'), ('medium', 'Medium (5-6)'), ('high', 'High (7+)')], default='low', max_length=20)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('calculated_by', models.ForeignKey(limit_choices_to={'role__in': ['nurse', 'doctor']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.tenantuser')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='early_warning_scores', to='patients.patient')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='early_warning_scores', to='tenants.tenant')),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='early_warning_scores', to='patients.patientvisit')),
            ],
            options={
                'verbose_name': 'Early Warning Score',
                'verbose_name_plural': 'Early Warning Scores',
                'ordering': ['-calculated_at'],
            },
        ),
        migrations.AddField(
            model_name='vitalsign',
            name='blood_glucose',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='vitalsign',
            name='consciousness',
            field=models.CharField(blank=True, choices=[('Alert', 'Alert'), ('Voice', 'Responds to Voice'), ('Pain', 'Responds to Pain'), ('Unresponsive', 'Unresponsive')], default='Alert', max_length=20),
        ),
        migrations.AlterField(
            model_name='vitalsign',
            name='pain_score',
            field=models.IntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2 - Mild'), (3, '3'), (4, '4 - Moderate'), (5, '5'), (6, '6'), (7, '7 - Severe'), (8, '8'), (9, '9'), (10, '10 - Worst')], null=True),
        ),
        migrations.CreateModel(
            name='VitalSignAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('alert_type', models.CharField(choices=[('early_warning', 'Early Warning Score'), ('bp_abnormal', 'Blood Pressure Abnormal'), ('fever', 'Fever / Temperature Abnormal'), ('tachycardia', 'Heart Rate Abnormal'), ('bradycardia', 'Heart Rate Abnormal'), ('tachypnoea', 'Respiratory Rate Abnormal'), ('hypoxia', 'Oxygen Saturation Low'), ('critical', 'Critical Alert'), ('custom', 'Custom Alert')], max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('notification_sent', models.BooleanField(default=False)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_vital_alerts', to='tenants.tenantuser')),
                ('early_warning_score', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='clinical.earlywarningscore')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vital_sign_alerts', to='patients.patient')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_vital_alerts', to='tenants.tenantuser')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vital_sign_alerts', to='tenants.tenant')),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vital_sign_alerts', to='patients.patientvisit')),
                ('vital_sign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='clinical.vitalsign')),
            ],
            options={
                'verbose_name': 'Vital Sign Alert',
                'verbose_name_plural': 'Vital Sign Alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='earlywarningscore',
            name='vital_sign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='early_warning_scores', to='clinical.vitalsign'),
        ),
    ]
