# Generated by Django 4.2.19 on 2026-08-07 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='globaluser',
            name='token_version',
            field=models.IntegerField(default=1),
        ),
    ]
