# Generated by Django 4.2.19 on 2026-08-08 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_globaluser_token_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globaluser',
            name='two_fa_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
