# Generated by Django 4.2.7 on 2026-07-01 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_passwordresettoken'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='passwordresettoken',
            new_name='users_passw_token_e5d3aa_idx',
            old_name='users_password_token_idx',
        ),
        migrations.RenameIndex(
            model_name='passwordresettoken',
            new_name='users_passw_email_4d06f3_idx',
            old_name='users_password_email_idx',
        ),
        migrations.AddField(
            model_name='passwordresettoken',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
