# Generated by Django 4.2.19 on 2026-08-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_globaluser_two_fa_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='globaluser',
            name='can_manage_admin_permissions',
            field=models.BooleanField(default=False),
        ),
    ]
