# Generated by Django 4.2.7 on 2026-07-01 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_users_password_token_idx_users_passw_token_e5d3aa_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globaluser',
            name='account_locked_until',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='globaluser',
            name='last_login_ip',
            field=models.GenericIPAddressField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='rsakey',
            name='expires_at',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='rsakey',
            name='last_used',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='securityevent',
            name='ip_address',
            field=models.GenericIPAddressField(db_index=True),
        ),
        migrations.AlterField(
            model_name='user2fa',
            name='failed_attempts',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='user2fa',
            name='last_failed_attempt',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='user2fa',
            name='last_used',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='expires_at',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='ip_address',
            field=models.GenericIPAddressField(db_index=True),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='last_activity',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='globaluser',
            index=models.Index(fields=['role', 'is_active'], name='users_globa_role_8bbc37_idx'),
        ),
        migrations.AddIndex(
            model_name='globaluser',
            index=models.Index(fields=['account_locked_until', 'is_active'], name='users_globa_account_fc895e_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordresettoken',
            index=models.Index(fields=['user_id', 'is_used'], name='users_passw_user_id_5ee9a9_idx'),
        ),
        migrations.AddIndex(
            model_name='rsakey',
            index=models.Index(fields=['is_primary', 'user'], name='users_rsake_is_prim_f892f3_idx'),
        ),
        migrations.AddIndex(
            model_name='rsakey',
            index=models.Index(fields=['expires_at', 'is_primary'], name='users_rsake_expires_357605_idx'),
        ),
        migrations.AddIndex(
            model_name='usernotification',
            index=models.Index(fields=['user', 'is_read', 'created_at'], name='users_usern_user_id_256340_idx'),
        ),
        migrations.AddIndex(
            model_name='usernotification',
            index=models.Index(fields=['notification_type', 'is_read'], name='users_usern_notific_868d8a_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['user', 'is_active', 'last_activity'], name='users_users_user_id_eea995_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['expires_at', 'is_active'], name='users_users_expires_45d8d1_idx'),
        ),
    ]
