# Generated by Django 4.2.7 on 2026-07-11 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auditlog_severity_title_actor_is_verified'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['severity', 'timestamp'], name='core_auditl_severit_4032b9_idx'),
        ),
    ]
