# Generated by Django 4.2.19 on 2026-08-28 18:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ward_rounds', '0001_initial'),
        ('patients', '0003_patient_mpi'),
        ('tenants', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPDStay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('admission_number', models.CharField(blank=True, max_length=40, unique=True)),
                ('diagnosis', models.TextField()),
                ('admission_reason', models.TextField(blank=True)),
                ('arrival_mode', models.CharField(choices=[('walk_in', 'Walk-in'), ('ambulance', 'Ambulance'), ('referral', 'Referral'), ('opd', 'OPD transfer')], default='walk_in', max_length=20)),
                ('status', models.CharField(choices=[('pre_admission', 'Pre-admission'), ('waiting', 'Waiting for bed'), ('admitted', 'Admitted'), ('discharged', 'Discharged'), ('transferred', 'Transferred out'), ('deceased', 'Deceased')], default='waiting', max_length=20)),
                ('emergency', models.BooleanField(default=False)),
                ('pre_authorization_number', models.CharField(blank=True, max_length=100)),
                ('expected_discharge_date', models.DateField(blank=True, null=True)),
                ('admitted_at', models.DateTimeField(blank=True, null=True)),
                ('discharged_at', models.DateTimeField(blank=True, null=True)),
                ('discharge_criteria', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('admitting_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ipd_admissions', to='tenants.tenantuser')),
                ('bed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ipd_stays', to='ward_rounds.bed')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ipd_stays', to='patients.patient')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ipd_stays', to='tenants.tenant')),
                ('ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ipd_stays', to='ward_rounds.ward')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NursingCarePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('goal', models.CharField(max_length=255)),
                ('intervention', models.TextField()),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ipd_care_plans', to='tenants.tenantuser')),
                ('stay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_plans', to='ipd.ipdstay')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MedicationAdministration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('medication_name', models.CharField(max_length=200)),
                ('dose', models.CharField(max_length=100)),
                ('route', models.CharField(max_length=50)),
                ('scheduled_at', models.DateTimeField()),
                ('administered_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('given', 'Given'), ('held', 'Held'), ('refused', 'Refused'), ('omitted', 'Omitted')], default='scheduled', max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('administered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ipd_medication_administrations', to='tenants.tenantuser')),
                ('stay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mar_entries', to='ipd.ipdstay')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IPDTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('reason', models.TextField()),
                ('escort_details', models.TextField(blank=True)),
                ('transferred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('from_bed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ipd_transfers_from', to='ward_rounds.bed')),
                ('from_ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ipd_transfers_from', to='ward_rounds.ward')),
                ('stay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='ipd.ipdstay')),
                ('to_bed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ipd_transfers_to', to='ward_rounds.bed')),
                ('to_ward', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ipd_transfers_to', to='ward_rounds.ward')),
                ('transferred_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ipd_transfers', to='tenants.tenantuser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IPDProgressNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('subjective', models.TextField(blank=True)),
                ('objective', models.TextField(blank=True)),
                ('assessment', models.TextField()),
                ('plan', models.TextField()),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ipd_progress_notes', to='tenants.tenantuser')),
                ('stay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_notes', to='ipd.ipdstay')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IPDDischarge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('diagnosis', models.TextField()),
                ('treatment_given', models.TextField(blank=True)),
                ('procedures', models.TextField(blank=True)),
                ('discharge_medications', models.JSONField(blank=True, default=list)),
                ('follow_up_advice', models.TextField(blank=True)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('billing_cleared', models.BooleanField(default=False)),
                ('summary_signed', models.BooleanField(default=False)),
                ('belongings_returned', models.BooleanField(default=False)),
                ('feedback_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('prepared_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ipd_discharges_prepared', to='tenants.tenantuser')),
                ('stay', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='discharge', to='ipd.ipdstay')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IntakeOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.CharField(choices=[('intake', 'Intake'), ('output', 'Output')], max_length=10)),
                ('item', models.CharField(max_length=100)),
                ('amount_ml', models.DecimalField(decimal_places=2, max_digits=8)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ipd_intake_outputs', to='tenants.tenantuser')),
                ('stay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intake_outputs', to='ipd.ipdstay')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='ipdstay',
            index=models.Index(fields=['tenant', 'status'], name='ipd_ipdstay_tenant__075e48_idx'),
        ),
        migrations.AddIndex(
            model_name='ipdstay',
            index=models.Index(fields=['patient', 'status'], name='ipd_ipdstay_patient_0e9c28_idx'),
        ),
    ]
