# Generated by Django 4.2.19 on 2026-08-28 18:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_initial'),
        ('ipd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPDWaitlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('requested_ward_type', models.CharField(max_length=100)),
                ('priority', models.CharField(default='normal', max_length=20)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('stay', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entry', to='ipd.ipdstay')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IPDClinicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('record_type', models.CharField(choices=[('shift_handover', 'Shift handover'), ('wound_care', 'Wound care'), ('patient_observation', 'Patient observation'), ('procedure_order', 'Procedure order'), ('specialist_referral', 'Specialist referral'), ('leave_of_absence', 'Leave of absence'), ('consent', 'Consent'), ('advance_directive', 'Advance directive'), ('medico_legal', 'Medico-legal case')], max_length=30)),
                ('status', models.CharField(default='open', max_length=30)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='ipd/clinical/')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ipd_clinical_records', to='tenants.tenantuser')),
                ('stay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_records', to='ipd.ipdstay')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IPDCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.CharField(max_length=255)),
                ('category', models.CharField(default='other', max_length=40)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('charge_date', models.DateField(default=django.utils.timezone.localdate)),
                ('source', models.CharField(default='manual', max_length=30)),
                ('posted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ipd_charges_posted', to='tenants.tenantuser')),
                ('stay', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='ipd.ipdstay')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
