# Generated by Django 4.2.7 on 2026-01-30 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantuser',
            name='global_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.specialization'),
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.state'),
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='tenantsetting',
            name='tenant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings_config', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='tenantmodule',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='tenantinvitation',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.department'),
        ),
        migrations.AddField(
            model_name='tenantinvitation',
            name='invited_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to='tenants.tenantuser'),
        ),
        migrations.AddField(
            model_name='tenantinvitation',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='tenantbackup',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backups', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='tenantactivitylog',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='tenantactivitylog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.tenantuser'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='tenants', to='core.country'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tenants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tenant',
            name='facility_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.facilitytype'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='lga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.lga'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.state'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='subscription_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='department',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to='tenants.tenantuser'),
        ),
        migrations.AddField(
            model_name='department',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='tenantuser',
            index=models.Index(fields=['tenant', 'username'], name='tenants_ten_tenant__346d71_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantuser',
            index=models.Index(fields=['tenant', 'email'], name='tenants_ten_tenant__205ae0_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantuser',
            index=models.Index(fields=['tenant', 'role'], name='tenants_ten_tenant__55a2cb_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantuser',
            index=models.Index(fields=['tenant', 'employee_id'], name='tenants_ten_tenant__94c685_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tenantuser',
            unique_together={('tenant', 'username'), ('tenant', 'email')},
        ),
        migrations.AlterUniqueTogether(
            name='tenantmodule',
            unique_together={('tenant', 'module_code')},
        ),
        migrations.AddIndex(
            model_name='tenantinvitation',
            index=models.Index(fields=['token'], name='tenants_ten_token_a4104e_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantinvitation',
            index=models.Index(fields=['email', 'status'], name='tenants_ten_email_bcd63e_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantactivitylog',
            index=models.Index(fields=['tenant', 'created_at'], name='tenants_ten_tenant__e94f31_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantactivitylog',
            index=models.Index(fields=['tenant', 'user', 'created_at'], name='tenants_ten_tenant__4f3651_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantactivitylog',
            index=models.Index(fields=['resource_type', 'resource_id'], name='tenants_ten_resourc_fc8c69_idx'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['domain'], name='tenants_ten_domain_a84b8d_idx'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['schema_name'], name='tenants_ten_schema__df93bb_idx'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['subscription_status'], name='tenants_ten_subscri_5ee30d_idx'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['nhis_accreditation'], name='tenants_ten_nhis_ac_dcb999_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('tenant', 'code')},
        ),
    ]
