# Generated by Django 4.2.19 on 2026-08-28 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalServiceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('mirth_endpoint', models.URLField(blank=True)),
                ('mirth_channel_id', models.CharField(blank=True, max_length=120)),
                ('mirth_api_key', models.CharField(blank=True, max_length=255)),
                ('lis_endpoint', models.URLField(blank=True)),
                ('lis_api_key', models.CharField(blank=True, max_length=255)),
                ('pacs_endpoint', models.URLField(blank=True)),
                ('pacs_api_key', models.CharField(blank=True, max_length=255)),
                ('fhir_endpoint', models.URLField(blank=True)),
                ('fhir_api_key', models.CharField(blank=True, max_length=255)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='external_service_profile', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'External Service Profile',
                'verbose_name_plural': 'External Service Profiles',
            },
        ),
    ]
