# Generated by Django 4.2.7 on 2026-07-01 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_tenantuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantuser',
            name='employment_status',
            field=models.CharField(choices=[('active', 'Active'), ('on_leave', 'On Leave'), ('suspended', 'Suspended'), ('terminated', 'Terminated'), ('retired', 'Retired')], db_index=True, default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='tenantuser',
            name='last_login_ip',
            field=models.GenericIPAddressField(blank=True, db_index=True, null=True),
        ),
    ]
