# Generated by Django 4.2.19 on 2026-08-07 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantuser',
            name='token_version',
            field=models.IntegerField(default=1),
        ),
    ]
