# Generated by Django 4.2.7 on 2026-07-01 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_alter_tenantuser_employment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantuser',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='tenantuser',
            name='username',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
