# Generated by Django 4.2.19 on 2026-08-31 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_externalserviceprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantinvitation',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('doctor', 'Doctor'), ('nurse', 'Nurse'), ('pharmacist', 'Pharmacist'), ('lab_tech', 'Lab Technician'), ('lab_manager', 'Lab Manager'), ('receptionist', 'Receptionist'), ('accountant', 'Accountant'), ('hr_manager', 'HR Manager'), ('inventory_manager', 'Inventory Manager'), ('patient', 'Patient')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tenantuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('doctor', 'Doctor'), ('nurse', 'Nurse'), ('pharmacist', 'Pharmacist'), ('lab_tech', 'Lab Technician'), ('lab_manager', 'Lab Manager'), ('receptionist', 'Receptionist'), ('accountant', 'Accountant'), ('hr_manager', 'HR Manager'), ('inventory_manager', 'Inventory Manager'), ('patient', 'Patient')], max_length=50),
        ),
    ]
