# Generated by Django 4.2.19 on 2026-08-08 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_tenantuser_token_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='email_limit_monthly',
            field=models.IntegerField(default=1000, help_text='Max emails per month'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='email_service_cost_monthly',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cost of email service provider per month', max_digits=12),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='service_providers',
            field=models.JSONField(blank=True, default=dict, help_text='Configured service providers, e.g. {"email": "sendgrid", "sms": "twilio"}'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='sms_limit_monthly',
            field=models.IntegerField(default=500, help_text='Max SMS per month'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='sms_service_cost_monthly',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cost of SMS service provider per month', max_digits=12),
        ),
    ]
