# Generated by Django 4.2.7 on 2026-06-20 22:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_tenantdomain'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
