# Generated by Django 4.2.19 on 2026-09-01 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_alter_tenantinvitation_role_alter_tenantuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionpayment',
            name='email_service_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Email service cost for this billing period', max_digits=12),
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='include_email_service',
            field=models.BooleanField(default=False, help_text='Whether email service is included in this subscription'),
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='include_sms_service',
            field=models.BooleanField(default=False, help_text='Whether SMS service is included in this subscription'),
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='sms_service_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='SMS service cost for this billing period', max_digits=12),
        ),
    ]
