# Generated by Django 4.2.7 on 2026-07-01 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_alter_tenantuser_email_alter_tenantuser_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenantuser',
            options={'ordering': ['tenant', 'username', 'email'], 'verbose_name': 'Tenant User', 'verbose_name_plural': 'Tenant Users'},
        ),
    ]
