# Generated by Django 4.2.19 on 2026-09-01 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_subscriptionpayment_email_service_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='email_service_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Current monthly email service cost', max_digits=12),
        ),
        migrations.AddField(
            model_name='tenant',
            name='include_email_service',
            field=models.BooleanField(default=False, help_text='Whether the tenant has email service enabled'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='include_sms_service',
            field=models.BooleanField(default=False, help_text='Whether the tenant has SMS service enabled'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='sms_service_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Current monthly SMS service cost', max_digits=12),
        ),
    ]
