# Generated by Django 4.2.7 on 2026-06-20 23:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_alter_tenant_nhis_provider_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='subscription_start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
