# Generated by Django 4.2.7 on 2026-07-03 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_alter_tenantuser_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantuser',
            name='is_root_admin',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='tenantuser',
            index=models.Index(fields=['tenant', 'is_root_admin'], name='tenants_ten_tenant__39aa4c_idx'),
        ),
        migrations.AddConstraint(
            model_name='tenantuser',
            constraint=models.UniqueConstraint(condition=models.Q(('is_root_admin', True)), fields=('tenant',), name='unique_root_admin_per_tenant'),
        ),
    ]
