# Generated by Django 4.2.19 on 2026-08-08 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_supportticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='created_by_email',
            field=models.EmailField(help_text='Email of person who created the ticket', max_length=254),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='created_by_name',
            field=models.CharField(help_text='Name of person who created the ticket', max_length=100),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='created_by_role',
            field=models.CharField(help_text='Role of creator (e.g. admin, receptionist)', max_length=50),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['tenant', 'status', '-created_at'], name='tenants_sup_tenant__d9f3a1_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['priority', '-created_at'], name='tenants_sup_priorit_8a87e1_idx'),
        ),
    ]
