# Generated by Django 4.2.7 on 2026-07-16 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_tenantuser_is_root_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantinvitation',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
