# Generated by Django 4.2.7 on 2026-06-20 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_alter_tenant_subscription_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantuser',
            name='username',
            field=models.CharField(blank=True, max_length=150, unique=True),
        ),
    ]
