# Generated by Django 4.2.7 on 2026-07-16 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_add_archived_to_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantuser',
            name='created_by_invitation',
            field=models.BooleanField(default=False),
        ),
    ]
