# Generated by Django 4.2.7 on 2026-06-29 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0002_bulkpatientupload'),
        ('tenants', '0002_tenantuser_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('record_type', models.CharField(choices=[('outpatient', 'Outpatient'), ('inpatient', 'Inpatient'), ('emergency', 'Emergency'), ('day_care', 'Day Care')], default='outpatient', max_length=20)),
                ('chief_complaint', models.TextField(blank=True)),
                ('history_of_present_illness', models.TextField(blank=True)),
                ('past_medical_history', models.TextField(blank=True)),
                ('family_history', models.TextField(blank=True)),
                ('social_history', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_records', to='tenants.tenantuser')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='patients.patient')),
                ('primary_doctor', models.ForeignKey(blank=True, limit_choices_to={'role': 'doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_records', to='tenants.tenantuser')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='tenants.tenant')),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_records', to='patients.patientvisit')),
            ],
            options={
                'verbose_name': 'Medical Record',
                'verbose_name_plural': 'Medical Records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClinicalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('document_type', models.CharField(choices=[('lab_result', 'Lab Result'), ('radiology', 'Radiology Report'), ('prescription', 'Prescription'), ('consent', 'Consent Form'), ('imaging', 'Medical Imaging'), ('photo', 'Clinical Photo'), ('referral', 'Referral Letter'), ('discharge', 'Discharge Summary'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='clinical_documents/%Y/%m/%d/')),
                ('file_url', models.URLField(blank=True)),
                ('mime_type', models.CharField(blank=True, max_length=50)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='emr.medicalrecord')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_documents', to='patients.patient')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_documents', to='tenants.tenant')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.tenantuser')),
            ],
            options={
                'verbose_name': 'Clinical Document',
                'verbose_name_plural': 'Clinical Documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('allergen', models.CharField(max_length=200)),
                ('allergy_type', models.CharField(choices=[('drug', 'Drug'), ('food', 'Food'), ('environmental', 'Environmental'), ('latex', 'Latex'), ('other', 'Other')], max_length=20)),
                ('reaction', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')], default='moderate', max_length=20)),
                ('first_identified', models.DateField(blank=True, null=True)),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergies', to='emr.medicalrecord')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emr_allergies', to='patients.patient')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergies', to='tenants.tenant')),
                ('verified_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.tenantuser')),
            ],
            options={
                'verbose_name': 'Allergy',
                'verbose_name_plural': 'Allergies',
                'ordering': ['-severity', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgressNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('subjective', models.TextField(blank=True)),
                ('objective', models.TextField(blank=True)),
                ('assessment', models.TextField(blank=True)),
                ('plan', models.TextField(blank=True)),
                ('note_type', models.CharField(choices=[('progress', 'Progress Note'), ('consultation', 'Consultation Note'), ('procedure', 'Procedure Note'), ('discharge', 'Discharge Summary'), ('transfer', 'Transfer Note'), ('admission', 'Admission Note'), ('nursing', 'Nursing Note')], default='progress', max_length=20)),
                ('is_signed', models.BooleanField(default=False)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(limit_choices_to={'role__in': ['doctor', 'nurse']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.tenantuser')),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_notes', to='emr.medicalrecord')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_notes', to='tenants.tenant')),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progress_notes', to='patients.patientvisit')),
            ],
            options={
                'verbose_name': 'Progress Note',
                'verbose_name_plural': 'Progress Notes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['medical_record', '-created_at'], name='emr_progres_medical_fe967c_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProblemList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('problem', models.CharField(max_length=200)),
                ('icd10_code', models.CharField(blank=True, max_length=20)),
                ('onset_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved'), ('chronic', 'Chronic')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('diagnosed_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.tenantuser')),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='emr.medicalrecord')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_list', to='patients.patient')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_list', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Problem List Entry',
                'verbose_name_plural': 'Problem List',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['medical_record', 'status'], name='emr_problem_medical_609de7_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='medicalrecord',
            index=models.Index(fields=['tenant', 'patient', '-created_at'], name='emr_medical_tenant__0fb88c_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalrecord',
            index=models.Index(fields=['record_number'], name='emr_medical_record__65f33f_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicaldocument',
            index=models.Index(fields=['medical_record', '-created_at'], name='emr_clinica_medical_5b75fd_idx'),
        ),
        migrations.AddIndex(
            model_name='allergy',
            index=models.Index(fields=['medical_record', '-created_at'], name='emr_allergy_medical_4b8dc5_idx'),
        ),
    ]
