# Generated by Django 4.2.19 on 2026-08-07 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        ('patients', '0001_initial'),
        ('emr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressnote',
            name='author',
            field=models.ForeignKey(limit_choices_to={'role__in': ['doctor', 'nurse']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.tenantuser'),
        ),
        migrations.AddField(
            model_name='progressnote',
            name='medical_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progress_notes', to='emr.medicalrecord'),
        ),
        migrations.AddField(
            model_name='progressnote',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_notes', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='progressnote',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progress_notes', to='patients.patientvisit'),
        ),
        migrations.AddField(
            model_name='problemlist',
            name='diagnosed_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.tenantuser'),
        ),
        migrations.AddField(
            model_name='problemlist',
            name='medical_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='emr.medicalrecord'),
        ),
        migrations.AddField(
            model_name='problemlist',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_list', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='problemlist',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_list', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_records', to='tenants.tenantuser'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='primary_doctor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_records', to='tenants.tenantuser'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_records', to='patients.patientvisit'),
        ),
        migrations.AddField(
            model_name='clinicaldocument',
            name='medical_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='emr.medicalrecord'),
        ),
        migrations.AddField(
            model_name='clinicaldocument',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_documents', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='clinicaldocument',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_documents', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='clinicaldocument',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.tenantuser'),
        ),
        migrations.AddField(
            model_name='allergy',
            name='medical_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergies', to='emr.medicalrecord'),
        ),
        migrations.AddField(
            model_name='allergy',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emr_allergies', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='allergy',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergies', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='allergy',
            name='verified_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.tenantuser'),
        ),
        migrations.AddIndex(
            model_name='progressnote',
            index=models.Index(fields=['medical_record', '-created_at'], name='emr_progres_medical_fe967c_idx'),
        ),
        migrations.AddIndex(
            model_name='problemlist',
            index=models.Index(fields=['medical_record', 'status'], name='emr_problem_medical_609de7_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalrecord',
            index=models.Index(fields=['tenant', 'patient', '-created_at'], name='emr_medical_tenant__0fb88c_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalrecord',
            index=models.Index(fields=['record_number'], name='emr_medical_record__65f33f_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicaldocument',
            index=models.Index(fields=['medical_record', '-created_at'], name='emr_clinica_medical_5b75fd_idx'),
        ),
        migrations.AddIndex(
            model_name='allergy',
            index=models.Index(fields=['medical_record', '-created_at'], name='emr_allergy_medical_4b8dc5_idx'),
        ),
    ]
