# Generated by Django 4.2.19 on 2026-08-21 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dispense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dispensed_date', models.DateTimeField(auto_now_add=True)),
                ('instructions', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Dispense',
                'verbose_name_plural': 'Dispenses',
                'ordering': ['-dispensed_date'],
            },
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200)),
                ('generic_name', models.CharField(blank=True, max_length=200)),
                ('brand_name', models.CharField(blank=True, max_length=200)),
                ('drug_code', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(choices=[('antibiotic', 'Antibiotic'), ('analgesic', 'Analgesic'), ('antihypertensive', 'Antihypertensive'), ('antidiabetic', 'Antidiabetic'), ('antimalarial', 'Antimalarial'), ('vaccine', 'Vaccine'), ('supplement', 'Supplement'), ('other', 'Other')], max_length=100)),
                ('form', models.CharField(choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('syrup', 'Syrup'), ('injection', 'Injection'), ('ointment', 'Ointment'), ('cream', 'Cream'), ('drops', 'Drops'), ('inhaler', 'Inhaler'), ('suppository', 'Suppository')], max_length=50)),
                ('strength', models.CharField(blank=True, max_length=100)),
                ('therapeutic_class', models.CharField(blank=True, max_length=100)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('reorder_level', models.IntegerField(default=10)),
                ('reorder_quantity', models.IntegerField(default=0)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unit_of_measure', models.CharField(blank=True, max_length=50)),
                ('batch_number', models.CharField(blank=True, max_length=100)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('storage_conditions', models.CharField(blank=True, max_length=200)),
                ('last_restocked', models.DateField(blank=True, null=True)),
                ('nafdac_number', models.CharField(blank=True, max_length=50)),
                ('pcn_approval_number', models.CharField(blank=True, max_length=50)),
                ('neml_category', models.CharField(blank=True, max_length=50)),
                ('manufacturer', models.CharField(blank=True, max_length=200)),
                ('supplier', models.CharField(blank=True, max_length=200)),
                ('country_of_origin', models.CharField(default='Nigeria', max_length=100)),
                ('is_controlled', models.BooleanField(default=False)),
                ('narcotic', models.BooleanField(default=False)),
                ('schedule', models.CharField(blank=True, max_length=50)),
                ('nhis_covered', models.BooleanField(default=False)),
                ('nhis_code', models.CharField(blank=True, max_length=50)),
                ('nhis_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('side_effects', models.TextField(blank=True)),
                ('contraindications', models.TextField(blank=True)),
                ('interactions', models.TextField(blank=True)),
                ('dosage_instructions', models.TextField(blank=True)),
                ('prescription_required', models.BooleanField(default=False)),
                ('barcode', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('discontinued', 'Discontinued')], default='active', max_length=20)),
            ],
            options={
                'verbose_name': 'Drug',
                'verbose_name_plural': 'Drugs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('nhis', 'NHIS'), ('hmo', 'HMO'), ('card', 'Card'), ('transfer', 'Transfer')], default='cash', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('partial', 'Partial'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='completed', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('sold_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sale',
                'verbose_name_plural': 'Sales',
                'ordering': ['-sold_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Sale Item',
                'verbose_name_plural': 'Sale Items',
                'ordering': ['sale', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('license_number', models.CharField(blank=True, max_length=100)),
                ('rating', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
                'ordering': ['name'],
            },
        ),
    ]
