# Generated by Django 4.2.7 on 2026-01-30 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        ('pharmacy', '0001_initial'),
        ('clinical', '0003_initial'),
        ('patients', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drugs', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='dispense',
            name='dispensed_by',
            field=models.ForeignKey(limit_choices_to={'role': 'pharmacist'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.tenantuser'),
        ),
        migrations.AddField(
            model_name='dispense',
            name='drug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispenses', to='pharmacy.drug'),
        ),
        migrations.AddField(
            model_name='dispense',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispenses', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='dispense',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispenses', to='clinical.prescription'),
        ),
        migrations.AddField(
            model_name='dispense',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispenses', to='tenants.tenant'),
        ),
    ]
