# Generated by Django 4.2.19 on 2026-09-05 06:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0006_tenant_email_service_cost_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('leave_type', models.CharField(choices=[('casual', 'Casual'), ('sick', 'Sick'), ('annual', 'Annual'), ('maternity', 'Maternity'), ('paternity', 'Paternity'), ('study', 'Study'), ('compensatory', 'Compensatory'), ('unpaid', 'Unpaid')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_days', models.PositiveIntegerField()),
                ('reason', models.TextField()),
                ('document', models.FileField(blank=True, null=True, upload_to='hr/leave-documents/')),
                ('alternate_contact', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('review_reason', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_applications', to='tenants.tenantuser')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_hr_leaves', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_leave_applications', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'status', 'start_date'], name='hr_leaveapp_tenant__778654_idx'), models.Index(fields=['tenant', 'employee', 'start_date'], name='hr_leaveapp_tenant__1274f1_idx')],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateField()),
                ('check_in', models.DateTimeField(blank=True, null=True)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('check_in_source', models.CharField(choices=[('biometric', 'Biometric'), ('manual', 'Manual'), ('face_id', 'Face ID'), ('mobile', 'Mobile')], default='manual', max_length=20)),
                ('check_out_source', models.CharField(choices=[('biometric', 'Biometric'), ('manual', 'Manual'), ('face_id', 'Face ID'), ('mobile', 'Mobile')], default='manual', max_length=20)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('half_day', 'Half-Day'), ('leave', 'Leave'), ('holiday', 'Holiday'), ('weekly_off', 'Weekly-Off')], default='present', max_length=20)),
                ('late_minutes', models.PositiveIntegerField(default=0)),
                ('early_minutes', models.PositiveIntegerField(default=0)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('shift_type', models.CharField(default='general', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='tenants.tenantuser')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_attendance', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-date', 'employee__first_name'],
                'indexes': [models.Index(fields=['tenant', 'date'], name='hr_attendan_tenant__e8a61b_idx'), models.Index(fields=['tenant', 'status', 'date'], name='hr_attendan_tenant__d7c81a_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.UniqueConstraint(fields=('tenant', 'employee', 'date'), name='unique_hr_attendance_day'),
        ),
    ]
