# Generated by Django 4.2.7 on 2026-06-30 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_tenantuser_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='WardRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ward_id', models.CharField(max_length=50)),
                ('ward_name', models.CharField(max_length=200)),
                ('round_type', models.CharField(choices=[('Daily Ward Round', 'Daily Ward Round'), ('Teaching Round', 'Teaching Round'), ('Grand Round', 'Grand Round'), ('Discharge Round', 'Discharge Round')], default='Daily Ward Round', max_length=30)),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=20)),
                ('date', models.DateTimeField()),
                ('time', models.TimeField()),
                ('consultant', models.CharField(max_length=200)),
                ('consultant_specialty', models.CharField(blank=True, max_length=200)),
                ('team_members', models.JSONField(blank=True, default=list)),
                ('patients_list', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('expected_duration', models.IntegerField(default=120, help_text='Duration in minutes')),
                ('actual_duration', models.IntegerField(blank=True, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('completed_time', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ward_rounds', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Ward Round',
                'verbose_name_plural': 'Ward Rounds',
                'ordering': ['-date', '-time'],
                'indexes': [models.Index(fields=['tenant', 'status', '-date'], name='ward_rounds_tenant__1cac5f_idx'), models.Index(fields=['ward_id', 'date'], name='ward_rounds_ward_id_0cb999_idx')],
            },
        ),
        migrations.CreateModel(
            name='HandoverNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ward_id', models.CharField(max_length=50)),
                ('ward_name', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('shift_from', models.CharField(max_length=50)),
                ('shift_to', models.CharField(max_length=50)),
                ('handover_officer', models.CharField(max_length=200)),
                ('receiving_officer', models.CharField(max_length=200)),
                ('critically_severe', models.JSONField(blank=True, default=list)),
                ('recent_admissions', models.JSONField(blank=True, default=list)),
                ('pending_procedures', models.JSONField(blank=True, default=list)),
                ('pending_discharges', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handover_notes', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Handover Note',
                'verbose_name_plural': 'Handover Notes',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['tenant', 'ward_id', '-date'], name='ward_rounds_tenant__cd673d_idx')],
            },
        ),
        migrations.CreateModel(
            name='GrandRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateTimeField()),
                ('time', models.TimeField()),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=20)),
                ('topic', models.CharField(max_length=300)),
                ('presenter', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('target_audience', models.TextField(blank=True)),
                ('case_studies', models.JSONField(blank=True, default=list)),
                ('expected_attendees', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grand_rounds', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Grand Round',
                'verbose_name_plural': 'Grand Rounds',
                'ordering': ['-date', '-time'],
                'indexes': [models.Index(fields=['tenant', 'status', '-date'], name='ward_rounds_tenant__5bcc85_idx')],
            },
        ),
    ]
