# Generated by Django 4.2.19 on 2026-09-03 21:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_tenant_email_service_cost_and_more'),
        ('patients', '0004_rename_patients_pa_tenant__a6a3c7_idx_patients_pa_tenant__dd8881_idx_and_more'),
        ('ward_rounds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyBay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('bay_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('bay_type', models.CharField(default='Standard', max_length=50)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_bays', to='tenants.tenant')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('tenant', 'bay_id')},
            },
        ),
        migrations.CreateModel(
            name='QualityImprovementPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=300)),
                ('source', models.CharField(blank=True, max_length=200)),
                ('objectives', models.TextField(blank=True)),
                ('responsible_person', models.CharField(blank=True, max_length=200)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='active', max_length=30)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('actions', models.JSONField(blank=True, default=list)),
                ('milestones', models.JSONField(blank=True, default=list)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_improvement_plans', to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PatientFeedbackRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('patient_name', models.CharField(blank=True, max_length=200)),
                ('rating', models.PositiveSmallIntegerField(default=0)),
                ('sentiment', models.CharField(blank=True, max_length=20)),
                ('comments', models.TextField(blank=True)),
                ('department', models.CharField(blank=True, max_length=200)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_records', to='patients.patient')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_records', to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PatientComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('patient_name', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('priority', models.CharField(default='medium', max_length=20)),
                ('description', models.TextField()),
                ('department', models.CharField(blank=True, max_length=200)),
                ('contact_method', models.CharField(default='phone', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('escalated', 'Escalated')], default='pending', max_length=20)),
                ('resolution', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='patients.patient')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_complaints', to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmergencyCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200)),
                ('age', models.PositiveIntegerField(default=0)),
                ('gender', models.CharField(blank=True, max_length=30)),
                ('presenting_complaint', models.TextField()),
                ('mode_of_arrival', models.CharField(default='Walk-in', max_length=50)),
                ('status', models.CharField(choices=[('waiting_triage', 'Waiting Triage'), ('triaged', 'Triaged'), ('in_treatment', 'In Treatment'), ('discharged', 'Discharged'), ('admitted', 'Admitted')], default='waiting_triage', max_length=30)),
                ('triage_score', models.IntegerField(blank=True, null=True)),
                ('triage_color', models.CharField(blank=True, max_length=20)),
                ('triage_data', models.JSONField(blank=True, default=dict)),
                ('arrival_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('triage_time', models.DateTimeField(blank=True, null=True)),
                ('treatment_start_time', models.DateTimeField(blank=True, null=True)),
                ('discharge_time', models.DateTimeField(blank=True, null=True)),
                ('disposition', models.CharField(blank=True, max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('assigned_bay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='ward_rounds.emergencybay')),
                ('assigned_nurse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_cases_as_nurse', to='tenants.tenantuser')),
                ('assigned_physician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_cases_as_physician', to='tenants.tenantuser')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_cases', to='patients.patient')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_cases', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-arrival_time'],
                'indexes': [models.Index(fields=['tenant', 'status', '-arrival_time'], name='ward_rounds_tenant__bf4aa0_idx')],
            },
        ),
    ]
