# Generated by Django 4.2.7 on 2026-06-30 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ward_rounds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wardround',
            name='round_documentation',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
