# Generated by Django 4.2.7 on 2026-07-01 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_alter_tenantuser_options'),
        ('patients', '0002_bulkpatientupload'),
        ('ward_rounds', '0002_wardround_round_documentation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ward_id', models.CharField(max_length=50)),
                ('ward_name', models.CharField(max_length=200)),
                ('ward_type', models.CharField(default='General Ward', max_length=100)),
                ('floor', models.CharField(blank=True, max_length=50)),
                ('supervisor', models.CharField(blank=True, max_length=200)),
                ('staff_count', models.PositiveIntegerField(default=0)),
                ('total_beds', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wards', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Ward',
                'verbose_name_plural': 'Wards',
                'ordering': ['ward_name'],
            },
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('bed_id', models.CharField(max_length=50)),
                ('bed_number', models.PositiveIntegerField()),
                ('bed_type', models.CharField(default='Standard', max_length=100)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Occupied', 'Occupied'), ('Reserved', 'Reserved'), ('Under Cleaning', 'Under Cleaning'), ('Maintenance', 'Maintenance')], default='Available', max_length=30)),
                ('is_private', models.BooleanField(default=False)),
                ('cleaning_status', models.CharField(choices=[('Clean', 'Clean'), ('Under Cleaning', 'Under Cleaning'), ('Maintenance', 'Maintenance')], default='Clean', max_length=30)),
                ('last_cleaned', models.DateTimeField(blank=True, null=True)),
                ('last_turnover', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beds', to='patients.patient')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='tenants.tenant')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='ward_rounds.ward')),
            ],
            options={
                'verbose_name': 'Bed',
                'verbose_name_plural': 'Beds',
                'ordering': ['ward', 'bed_number'],
            },
        ),
        migrations.AddIndex(
            model_name='ward',
            index=models.Index(fields=['tenant', 'ward_id'], name='ward_rounds_tenant__1c6cb2_idx'),
        ),
        migrations.AddIndex(
            model_name='ward',
            index=models.Index(fields=['ward_name'], name='ward_rounds_ward_na_410a36_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ward',
            unique_together={('tenant', 'ward_id')},
        ),
        migrations.AddIndex(
            model_name='bed',
            index=models.Index(fields=['tenant', 'ward', 'status'], name='ward_rounds_tenant__1ae80d_idx'),
        ),
        migrations.AddIndex(
            model_name='bed',
            index=models.Index(fields=['ward', 'bed_number'], name='ward_rounds_ward_id_66aecb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bed',
            unique_together={('ward', 'bed_id'), ('ward', 'bed_number')},
        ),
    ]
