# Generated by Django 4.2.19 on 2026-09-03 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_tenant_email_service_cost_and_more'),
        ('ward_rounds', '0002_emergencybay_qualityimprovementplan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=300)),
                ('type', models.CharField(default='post_visit', max_length=50)),
                ('questions', models.JSONField(blank=True, default=list)),
                ('target_audience', models.CharField(default='all_patients', max_length=100)),
                ('distribution_method', models.CharField(default='sms', max_length=30)),
                ('scheduled_date', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(default='draft', max_length=30)),
                ('responses', models.PositiveIntegerField(default=0)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_surveys', to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
