# Generated by Django 4.2.19 on 2026-09-03 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_tenant_email_service_cost_and_more'),
        ('ward_rounds', '0003_patientsurvey'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambulance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ambulance_id', models.CharField(max_length=50)),
                ('vehicle_number', models.CharField(max_length=100)),
                ('ambulance_type', models.CharField(default='BLS', max_length=50)),
                ('status', models.CharField(default='Available', max_length=50)),
                ('location', models.JSONField(blank=True, default=dict)),
                ('fuel_level', models.PositiveSmallIntegerField(default=0)),
                ('mileage', models.PositiveIntegerField(default=0)),
                ('equipment', models.JSONField(blank=True, default=list)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ambulances', to='tenants.tenant')),
            ],
            options={
                'ordering': ['vehicle_number'],
                'unique_together': {('tenant', 'ambulance_id')},
            },
        ),
    ]
