# Generated by Django 4.2.7 on 2026-07-02 04:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_alter_tenantuser_options'),
        ('ward_rounds', '0003_ward_bed_ward_ward_rounds_tenant__1c6cb2_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('request_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('patient_id', models.CharField(max_length=50)),
                ('patient_name', models.CharField(max_length=200)),
                ('request_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('source', models.CharField(default='Direct Admission', max_length=100)),
                ('diagnosis', models.TextField(blank=True)),
                ('preferred_ward_type', models.CharField(blank=True, max_length=100)),
                ('priority', models.CharField(default='Medium', max_length=20)),
                ('status', models.CharField(choices=[('Requested', 'Requested'), ('Approved', 'Approved'), ('Admitted', 'Admitted'), ('Discharged', 'Discharged'), ('Transferred', 'Transferred'), ('Rejected', 'Rejected')], default='Requested', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('ward_id', models.CharField(blank=True, max_length=50)),
                ('bed_id', models.CharField(blank=True, max_length=50)),
                ('consultant_name', models.CharField(blank=True, max_length=200)),
                ('consultant_specialty', models.CharField(blank=True, max_length=200)),
                ('expected_stay', models.PositiveIntegerField(default=0)),
                ('planned_discharge_date', models.DateTimeField(blank=True, null=True)),
                ('actual_stay', models.PositiveIntegerField(blank=True, null=True)),
                ('date_of_admission', models.DateTimeField(blank=True, null=True)),
                ('discharge_date', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Admission',
                'verbose_name_plural': 'Admissions',
                'ordering': ['-request_date'],
                'indexes': [models.Index(fields=['tenant', 'status', '-request_date'], name='ward_rounds_tenant__8ad210_idx'), models.Index(fields=['tenant', 'patient_id'], name='ward_rounds_tenant__5327d9_idx')],
            },
        ),
    ]
