# Generated by Django 4.2.7 on 2026-07-02 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ward_rounds', '0004_admission'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='discharge_summary',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='admission',
            name='transfer_history',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
