# Generated by Django 4.2.19 on 2026-09-03 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_tenant_email_service_cost_and_more'),
        ('ward_rounds', '0004_ambulance'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambulancemission',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ambulance_missions', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='emergencycall',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emergency_calls', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='referralrequest',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referral_requests', to='tenants.tenant'),
        ),
    ]
