# Generated by Django 4.2.19 on 2026-09-04 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_rename_patients_pa_tenant__a6a3c7_idx_patients_pa_tenant__dd8881_idx_and_more'),
        ('ward_rounds', '0005_ambulancemission_tenant_emergencycall_tenant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambulancemission',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ambulance_missions', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='emergencycall',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_calls', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='referralrequest',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_requests', to='patients.patient'),
        ),
    ]
