# Generated by Django 4.2.7 on 2026-07-02 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_alter_tenantuser_options'),
        ('ward_rounds', '0006_ambulancemission_emergencycall_referralrequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dutyassignment',
            name='staff_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duty_assignments', to='tenants.tenantuser'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='staff_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_requests', to='tenants.tenantuser'),
        ),
        migrations.AddField(
            model_name='overtimerecord',
            name='staff_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overtime_records', to='tenants.tenantuser'),
        ),
        migrations.AddField(
            model_name='performanceappraisal',
            name='rater_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appraisals_created', to='tenants.tenantuser'),
        ),
        migrations.AddField(
            model_name='performanceappraisal',
            name='staff_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performance_appraisals', to='tenants.tenantuser'),
        ),
        migrations.AddField(
            model_name='performanceaudit',
            name='auditor_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audits_conducted', to='tenants.tenantuser'),
        ),
        migrations.AddField(
            model_name='performanceincident',
            name='staff_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performance_incidents', to='tenants.tenantuser'),
        ),
        migrations.AddField(
            model_name='researchoutput',
            name='staff_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='research_outputs', to='tenants.tenantuser'),
        ),
        migrations.AddField(
            model_name='satisfactionsurvey',
            name='staff_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='satisfaction_surveys', to='tenants.tenantuser'),
        ),
        migrations.AddField(
            model_name='teachingactivity',
            name='staff_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_activities', to='tenants.tenantuser'),
        ),
    ]
