# Generated by Django 4.2.19 on 2026-08-03 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ward_rounds', '0007_dutyassignment_staff_user_leaverequest_staff_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='overtimerecord',
            name='approval_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
