# Generated by Django 4.2.19 on 2026-09-30 21:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0006_tenant_email_service_cost_and_more'),
        ('patients', '0005_patient_registration_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('kind', models.CharField(choices=[('patient', 'Patient support'), ('staff', 'Staff chat')], max_length=16)),
                ('subject', models.CharField(max_length=180)),
                ('status', models.CharField(choices=[('open', 'Open'), ('pending', 'Pending'), ('closed', 'Closed')], default='open', max_length=16)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=16)),
                ('last_message_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_conversations', to='tenants.tenantuser')),
                ('opened_by_patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opened_conversations', to='patients.patient')),
                ('opened_by_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opened_conversations', to='tenants.tenantuser')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='patients.patient')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messaging_conversations', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-last_message_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('body', models.TextField(max_length=5000)),
                ('is_internal_note', models.BooleanField(default=False)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messaging.conversation')),
                ('sender_patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to='patients.patient')),
                ('sender_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to='tenants.tenantuser')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messaging_messages', to='tenants.tenant')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ConversationParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_read_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='messaging.conversation')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_participations', to='patients.patient')),
                ('tenant_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_participations', to='tenants.tenantuser')),
            ],
        ),
        migrations.CreateModel(
            name='MessagingNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=120)),
                ('message', models.CharField(max_length=200)),
                ('read_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_notifications', to='messaging.conversation')),
                ('recipient_patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_notifications', to='patients.patient')),
                ('recipient_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_notifications', to='tenants.tenantuser')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messaging_notifications', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient_staff', 'read_at', 'created_at'], name='messaging_notice_staff_idx'), models.Index(fields=['recipient_patient', 'read_at', 'created_at'], name='messaging_notice_patient_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='messagingnotification',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('recipient_patient__isnull', True), ('recipient_staff__isnull', False)), models.Q(('recipient_patient__isnull', False), ('recipient_staff__isnull', True)), _connector='OR'), name='messaging_notification_one_recipient'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='messaging_msg_conv_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('sender_patient__isnull', True), ('sender_staff__isnull', False)), models.Q(('sender_patient__isnull', False), ('sender_staff__isnull', True)), _connector='OR'), name='messaging_message_one_sender'),
        ),
        migrations.AddConstraint(
            model_name='conversationparticipant',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('patient__isnull', True), ('tenant_user__isnull', False)), models.Q(('patient__isnull', False), ('tenant_user__isnull', True)), _connector='OR'), name='messaging_participant_one_identity'),
        ),
        migrations.AddConstraint(
            model_name='conversationparticipant',
            constraint=models.UniqueConstraint(condition=models.Q(('tenant_user__isnull', False)), fields=('conversation', 'tenant_user'), name='messaging_unique_staff_participant'),
        ),
        migrations.AddConstraint(
            model_name='conversationparticipant',
            constraint=models.UniqueConstraint(condition=models.Q(('patient__isnull', False)), fields=('conversation', 'patient'), name='messaging_unique_patient_participant'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['tenant', 'kind', 'status', 'last_message_at'], name='messaging_conv_tenant_kind_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['tenant', 'assigned_to', 'status'], name='messaging_conv_assignee_idx'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('kind', 'patient'), ('opened_by_patient__isnull', False), ('opened_by_staff__isnull', True), ('patient__isnull', False)), models.Q(('kind', 'staff'), ('opened_by_patient__isnull', True), ('opened_by_staff__isnull', False), ('patient__isnull', True)), _connector='OR'), name='messaging_conversation_kind_subject'),
        ),
    ]
