# Generated by Django 4.2.19 on 2026-08-22 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('period', models.CharField(choices=[('annual', 'Annual'), ('quarterly', 'Quarterly'), ('monthly', 'Monthly')], default='annual', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('utilized', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('pending', 'Pending Approval'), ('rejected', 'Rejected'), ('active', 'Active'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('approval_required', models.BooleanField(default=False)),
                ('approved_by', models.CharField(blank=True, max_length=200)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Budget',
                'verbose_name_plural': 'Budgets',
                'ordering': ['-year', 'department'],
            },
        ),
        migrations.CreateModel(
            name='BudgetReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('report_type', models.CharField(choices=[('annual_budget', 'Annual Budget Report'), ('variance_analysis', 'Variance Analysis Report'), ('forecast_accuracy', 'Forecast Accuracy Report'), ('grant_utilization', 'Grant Utilization Report'), ('departmental', 'Departmental Report'), ('custom', 'Custom Report')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('generated_by', models.CharField(blank=True, max_length=200)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('summary', models.TextField(blank=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_reports', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Budget Report',
                'verbose_name_plural': 'Budget Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200)),
                ('donor', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('purpose', models.TextField()),
                ('conditions', models.TextField(blank=True)),
                ('contact_person', models.CharField(blank=True, max_length=200)),
                ('reporting_frequency', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semi_annual', 'Semi-Annual'), ('annual', 'Annual')], default='quarterly', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('suspended', 'Suspended'), ('terminated', 'Terminated')], default='active', max_length=20)),
                ('utilized', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('last_report_date', models.DateField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Grant',
                'verbose_name_plural': 'Grants',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['tenant', 'status', '-start_date'], name='budgeting_g_tenant__cce3d3_idx')],
            },
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.CharField(max_length=100)),
                ('period', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual')], default='quarterly', max_length=20)),
                ('year', models.PositiveIntegerField()),
                ('predicted_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('confidence_level', models.PositiveIntegerField(default=0)),
                ('assumptions', models.TextField(blank=True)),
                ('methodology', models.TextField(blank=True)),
                ('accuracy', models.PositiveIntegerField(default=0)),
                ('actual_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Forecast',
                'verbose_name_plural': 'Forecasts',
                'ordering': ['-year', 'category'],
                'indexes': [models.Index(fields=['tenant', 'category', 'year'], name='budgeting_f_tenant__5f1f12_idx')],
            },
        ),
        migrations.CreateModel(
            name='BudgetVariance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('period', models.CharField(max_length=20)),
                ('year', models.PositiveIntegerField()),
                ('planned_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('actual_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('variance_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('variance_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('notes', models.TextField(blank=True)),
                ('alert_triggered', models.BooleanField(default=False)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variances', to='budgeting.budget')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_variances', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Budget Variance',
                'verbose_name_plural': 'Budget Variances',
                'ordering': ['-year', 'period'],
                'indexes': [models.Index(fields=['tenant', 'budget', '-year'], name='budgeting_b_tenant__ef6936_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['tenant', 'department', 'year'], name='budgeting_b_tenant__c5601f_idx'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['tenant', 'status', '-year'], name='budgeting_b_tenant__9b7e4d_idx'),
        ),
    ]
