# Generated by Django 4.2.19 on 2026-08-21 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cds', '0001_initial'),
        ('tenants', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskassessment',
            name='calculated_by',
            field=models.ForeignKey(limit_choices_to={'role__in': ['doctor', 'nurse']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.tenantuser'),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_assessments', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_assessments', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='patientalert',
            name='acknowledged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_cds_alerts', to='tenants.tenantuser'),
        ),
        migrations.AddField(
            model_name='patientalert',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_alerts', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='patientalert',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_alerts', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='druginteraction',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drug_interactions', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='dosingguideline',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dosing_guidelines', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='clinicalguideline',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_guidelines', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='allergycheck',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergy_checks', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='allergycheck',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergy_checks', to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='patientalert',
            index=models.Index(fields=['tenant', 'patient', 'acknowledged', 'dismissed'], name='cds_patient_tenant__6fe47a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='druginteraction',
            unique_together={('tenant', 'drug1', 'drug2')},
        ),
        migrations.AddIndex(
            model_name='clinicalguideline',
            index=models.Index(fields=['tenant', 'category', '-created_at'], name='cds_clinica_tenant__681a80_idx'),
        ),
    ]
