# Generated by Django 4.2.7 on 2026-06-29 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0002_bulkpatientupload'),
        ('tenants', '0002_tenantuser_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=300)),
                ('audit_type', models.CharField(choices=[('clinical', 'Clinical Audit'), ('administrative', 'Administrative Audit'), ('quality', 'Quality Assurance'), ('compliance', 'Compliance Audit'), ('peer_review', 'Peer Review')], default='clinical', max_length=30)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('department', models.CharField(max_length=100)),
                ('auditor', models.CharField(max_length=200)),
                ('scheduled_date', models.DateTimeField()),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('findings', models.JSONField(blank=True, default=list)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('action_plan', models.JSONField(blank=True, default=list)),
                ('follow_up_date', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_audits', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Clinical Audit',
                'verbose_name_plural': 'Clinical Audits',
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='QualityIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('clinical', 'Clinical Quality'), ('safety', 'Patient Safety'), ('efficiency', 'Operational Efficiency'), ('satisfaction', 'Patient Satisfaction'), ('compliance', 'Compliance')], default='clinical', max_length=30)),
                ('target', models.CharField(max_length=50)),
                ('current', models.CharField(max_length=50)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annually')], default='monthly', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('warning', 'Warning'), ('critical', 'Critical')], default='good', max_length=20)),
                ('history', models.JSONField(blank=True, default=list)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_indicators', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Quality Indicator',
                'verbose_name_plural': 'Quality Indicators',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PeerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=300)),
                ('scheduled_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('reviewers', models.JSONField(default=list)),
                ('cases_count', models.IntegerField(default=0)),
                ('recommendations_count', models.IntegerField(default=0)),
                ('findings', models.JSONField(blank=True, default=list)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_reviews', to='audit.clinicalaudit')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_reviews', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Peer Review',
                'verbose_name_plural': 'Peer Reviews',
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='MortalityReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('case_type', models.CharField(max_length=200)),
                ('incident_date', models.DateTimeField()),
                ('review_date', models.DateTimeField()),
                ('department', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('summary', models.TextField()),
                ('root_cause', models.TextField(blank=True)),
                ('attendees', models.JSONField(default=list)),
                ('lessons_learned', models.JSONField(blank=True, default=list)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('action_items', models.JSONField(blank=True, default=list)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mortality_reviews', to='patients.patient')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mortality_reviews', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Mortality Review',
                'verbose_name_plural': 'Mortality Reviews',
                'ordering': ['-incident_date'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('protocol', models.CharField(choices=[('antibiotic_stewardship', 'Antibiotic Stewardship'), ('surgical_safety', 'Surgical Safety Checklist'), ('blood_transfusion', 'Blood Transfusion Protocol'), ('infection_control', 'Infection Control Measures'), ('medication_reconciliation', 'Medication Reconciliation'), ('pain_management', 'Pain Management Protocol')], max_length=50)),
                ('score', models.FloatField()),
                ('target', models.FloatField()),
                ('department', models.CharField(blank=True, max_length=100)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('findings', models.JSONField(blank=True, default=list)),
                ('improvement_areas', models.JSONField(blank=True, default=list)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_scores', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Compliance Score',
                'verbose_name_plural': 'Compliance Scores',
                'ordering': ['-period_end', 'protocol'],
                'unique_together': {('tenant', 'protocol', 'department', 'period_start', 'period_end')},
            },
        ),
        migrations.AddIndex(
            model_name='clinicalaudit',
            index=models.Index(fields=['tenant', 'status', '-scheduled_date'], name='audit_clini_tenant__d6c91d_idx'),
        ),
    ]
