# Generated by Django 4.2.19 on 2026-08-07 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        ('patients', '0001_initial'),
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualityindicator',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_indicators', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='peerreview',
            name='audit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_reviews', to='audit.clinicalaudit'),
        ),
        migrations.AddField(
            model_name='peerreview',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_reviews', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='mortalityreview',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mortality_reviews', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='mortalityreview',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mortality_reviews', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='compliancescore',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_scores', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='clinicalaudit',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_audits', to='tenants.tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='compliancescore',
            unique_together={('tenant', 'protocol', 'department', 'period_start', 'period_end')},
        ),
        migrations.AddIndex(
            model_name='clinicalaudit',
            index=models.Index(fields=['tenant', 'status', '-scheduled_date'], name='audit_clini_tenant__d6c91d_idx'),
        ),
    ]
