# Generated by Django 4.2.7 on 2026-06-23 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order_number', models.CharField(max_length=50, unique=True)),
                ('clinical_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ordered', 'Ordered'), ('collected', 'Sample Collected'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='ordered', max_length=20)),
                ('priority', models.CharField(choices=[('routine', 'Routine'), ('priority', 'Priority'), ('stat', 'STAT')], default='routine', max_length=20)),
                ('ordered_date', models.DateTimeField(auto_now_add=True)),
                ('collected_date', models.DateTimeField(blank=True, null=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('sample_accession_number', models.CharField(blank=True, max_length=50)),
                ('collected_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'lab_tech'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_orders', to='tenants.tenantuser')),
                ('ordered_by', models.ForeignKey(limit_choices_to={'role': 'doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.tenantuser')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_orders', to='patients.patient')),
                ('performed_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'lab_tech'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_orders', to='tenants.tenantuser')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_orders', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Lab Order',
                'verbose_name_plural': 'Lab Orders',
                'ordering': ['-ordered_date'],
            },
        ),
        migrations.CreateModel(
            name='NCDCReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('report_type', models.CharField(choices=[('lassa_fever', 'Lassa Fever'), ('cholera', 'Cholera'), ('yellow_fever', 'Yellow Fever'), ('measles', 'Measles'), ('meningitis', 'Meningitis'), ('covid19', 'COVID-19'), ('other', 'Other Notifiable Disease')], max_length=100)),
                ('case_count', models.IntegerField(default=1)),
                ('lga', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('acknowledged', 'Acknowledged'), ('investigating', 'Under Investigation'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('ncdc_reference', models.CharField(blank=True, max_length=50)),
                ('submitted_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.patient')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ncdc_reports', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'NCDC Report',
                'verbose_name_plural': 'NCDC Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(choices=[('hematology', 'Hematology'), ('biochemistry', 'Biochemistry'), ('microbiology', 'Microbiology'), ('urinalysis', 'Urinalysis'), ('hormonal', 'Hormonal'), ('immunology', 'Immunology'), ('molecular', 'Molecular'), ('other', 'Other')], max_length=100)),
                ('sample_type', models.CharField(max_length=100)),
                ('turnaround_time', models.IntegerField(help_text='Turnaround time in hours')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('reference_range', models.TextField(blank=True)),
                ('units', models.CharField(blank=True, max_length=50)),
                ('critical_low', models.CharField(blank=True, help_text='Critical low value', max_length=50)),
                ('critical_high', models.CharField(blank=True, help_text='Critical high value', max_length=50)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_tests', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Lab Test',
                'verbose_name_plural': 'Lab Tests',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('value', models.CharField(max_length=200)),
                ('value_numeric', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('units', models.CharField(blank=True, max_length=50)),
                ('reference_range', models.TextField(blank=True)),
                ('reference_low', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('reference_high', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('is_critical', models.BooleanField(default=False)),
                ('flag', models.CharField(choices=[('L', 'Low'), ('H', 'High'), ('LL', 'Critical Low'), ('HH', 'Critical High'), ('A', 'Abnormal'), ('', 'Normal')], default='', max_length=10)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_date', models.DateTimeField(blank=True, null=True)),
                ('result_notes', models.TextField(blank=True)),
                ('instrument_reading', models.TextField(blank=True, help_text='Raw data from instrument')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='lab.laborder')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_results', to='tenants.tenant')),
                ('verified_by', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['lab_tech', 'lab_manager']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_results', to='tenants.tenantuser')),
            ],
            options={
                'verbose_name': 'Lab Result',
                'verbose_name_plural': 'Lab Results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='laborder',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='lab.labtest'),
        ),
        migrations.AddField(
            model_name='laborder',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab_orders', to='patients.patientvisit'),
        ),
        migrations.CreateModel(
            name='InstrumentMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('instrument_name', models.CharField(max_length=200)),
                ('instrument_type', models.CharField(max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('maintenance_type', models.CharField(choices=[('routine', 'Routine Maintenance'), ('calibration', 'Calibration'), ('repair', 'Repair'), ('inspection', 'Inspection'), ('emergency', 'Emergency Repair')], max_length=50)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('scheduled_date', models.DateTimeField()),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('performed_by', models.CharField(blank=True, max_length=200)),
                ('vendor_name', models.CharField(blank=True, max_length=200)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instrument_maintenance', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Instrument Maintenance',
                'verbose_name_plural': 'Instrument Maintenances',
                'ordering': ['-scheduled_date'],
            },
        ),
    ]
