# Generated by Django 4.2.7 on 2026-01-30 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        ('lab', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_tests', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='laborder',
            name='collected_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'lab_tech'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_orders', to='tenants.tenantuser'),
        ),
        migrations.AddField(
            model_name='laborder',
            name='ordered_by',
            field=models.ForeignKey(limit_choices_to={'role': 'doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.tenantuser'),
        ),
        migrations.AddField(
            model_name='laborder',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_orders', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='laborder',
            name='performed_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'lab_tech'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_orders', to='tenants.tenantuser'),
        ),
        migrations.AddField(
            model_name='laborder',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_orders', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='laborder',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='lab.labtest'),
        ),
        migrations.AddField(
            model_name='laborder',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab_orders', to='patients.patientvisit'),
        ),
    ]
