# Generated by Django 4.2.19 on 2026-08-21 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lab', '0002_initial'),
        ('tenants', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ncdcreport',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ncdc_reports', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='labtest',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_tests', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='labresult',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='lab.laborder'),
        ),
        migrations.AddField(
            model_name='labresult',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_results', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='labresult',
            name='verified_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['lab_tech', 'lab_manager']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_results', to='tenants.tenantuser'),
        ),
        migrations.AddField(
            model_name='laborder',
            name='collected_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'lab_tech'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_orders', to='tenants.tenantuser'),
        ),
        migrations.AddField(
            model_name='laborder',
            name='ordered_by',
            field=models.ForeignKey(limit_choices_to={'role': 'doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.tenantuser'),
        ),
        migrations.AddField(
            model_name='laborder',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_orders', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='laborder',
            name='performed_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'lab_tech'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_orders', to='tenants.tenantuser'),
        ),
        migrations.AddField(
            model_name='laborder',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_orders', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='laborder',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='lab.labtest'),
        ),
        migrations.AddField(
            model_name='laborder',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab_orders', to='patients.patientvisit'),
        ),
        migrations.AddField(
            model_name='instrumentmaintenance',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instrument_maintenance', to='tenants.tenant'),
        ),
    ]
