# Generated by Django 4.2.19 on 2026-08-07 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('report_type', models.CharField(choices=[('consent_audit', 'Consent Audit Report'), ('data_subject_rights', 'Data Subject Rights Report'), ('breach_incident', 'Breach Incident Report'), ('annual_compliance', 'Annual NDPR Compliance'), ('training_compliance', 'Training Compliance Report'), ('third_party_review', 'Third Party Review')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('summary', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Compliance Report',
                'verbose_name_plural': 'Compliance Reports',
                'ordering': ['-period_end', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('patient_id', models.CharField(db_index=True, max_length=50)),
                ('patient_name', models.CharField(max_length=200)),
                ('consent_type', models.CharField(choices=[('treatment', 'Treatment & Care'), ('data_processing', 'Data Processing'), ('research', 'Research Participation'), ('marketing', 'Marketing Communications'), ('third_party', 'Third Party Sharing')], max_length=30)),
                ('purpose', models.TextField()),
                ('data_categories', models.JSONField(blank=True, default=list)),
                ('retention_period', models.CharField(blank=True, max_length=20)),
                ('third_parties', models.JSONField(blank=True, default=list)),
                ('consent_method', models.CharField(choices=[('digital', 'Digital Signature'), ('paper', 'Paper Form'), ('verbal', 'Verbal Consent'), ('implied', 'Implied Consent')], default='digital', max_length=20)),
                ('witness_name', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('withdrawn', 'Withdrawn'), ('pending', 'Pending')], default='active', max_length=20)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('withdrawal_reason', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Consent Record',
                'verbose_name_plural': 'Consent Records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataBreach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('breach_type', models.CharField(choices=[('unauthorized_access', 'Unauthorized Access'), ('data_loss', 'Data Loss/Theft'), ('hacking', 'Hacking/Cyber Attack'), ('physical_theft', 'Physical Theft'), ('accidental_disclosure', 'Accidental Disclosure'), ('system_failure', 'System Failure'), ('other', 'Other')], max_length=30)),
                ('affected_data', models.JSONField(blank=True, default=list)),
                ('affected_individuals', models.PositiveIntegerField(default=0)),
                ('breach_date', models.DateTimeField()),
                ('discovery_date', models.DateTimeField()),
                ('description', models.TextField()),
                ('containment_actions', models.TextField()),
                ('impact_assessment', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('investigating', 'Investigating'), ('contained', 'Contained'), ('resolved', 'Resolved'), ('reported', 'Reported to NITDA')], default='investigating', max_length=20)),
                ('reported_to_nitda', models.BooleanField(default=False)),
                ('nitda_report_date', models.DateTimeField(blank=True, null=True)),
                ('notification_sent', models.BooleanField(default=False)),
                ('notifications_sent_count', models.PositiveIntegerField(default=0)),
                ('response_time_hours', models.FloatField(default=0.0)),
                ('investigation_findings', models.TextField(blank=True)),
                ('preventive_actions', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Data Breach',
                'verbose_name_plural': 'Data Breaches',
                'ordering': ['-breach_date'],
            },
        ),
        migrations.CreateModel(
            name='DataSubjectRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('requester_type', models.CharField(choices=[('data_subject', 'Data Subject'), ('legal_representative', 'Legal Representative'), ('regulatory_authority', 'Regulatory Authority'), ('other', 'Other')], max_length=30)),
                ('requester_name', models.CharField(max_length=200)),
                ('requester_contact', models.CharField(max_length=200)),
                ('request_type', models.CharField(choices=[('access', 'Right to Access'), ('rectification', 'Right to Rectification'), ('erasure', 'Right to Erasure'), ('restriction', 'Right to Restriction'), ('portability', 'Right to Data Portability'), ('object', 'Right to Object'), ('other', 'Other')], max_length=30)),
                ('data_categories', models.JSONField(blank=True, default=list)),
                ('reason', models.TextField()),
                ('urgency', models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent'), ('critical', 'Critical')], default='normal', max_length=20)),
                ('identity_verification', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('partially_completed', 'Partially Completed')], default='pending', max_length=30)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_time', models.CharField(blank=True, max_length=50)),
                ('response', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Data Subject Request',
                'verbose_name_plural': 'Data Subject Requests',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='NDPRAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('action', models.CharField(choices=[('consent_created', 'Consent Created'), ('consent_updated', 'Consent Updated'), ('consent_withdrawn', 'Consent Withdrawn'), ('data_accessed', 'Data Accessed'), ('data_exported', 'Data Exported'), ('data_requested', 'Data Requested'), ('breach_reported', 'Breach Reported'), ('settings_updated', 'Settings Updated')], max_length=30)),
                ('description', models.TextField()),
                ('resource_type', models.CharField(blank=True, max_length=50)),
                ('resource_id', models.CharField(blank=True, max_length=50)),
                ('patient_id', models.CharField(blank=True, max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'NDPR Audit Log',
                'verbose_name_plural': 'NDPR Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
