# Generated by Django 4.2.19 on 2026-08-21 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ndpr', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ndprauditlog',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ndpr_audit_logs', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='ndprauditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ndpr_audit_logs', to='tenants.tenantuser'),
        ),
        migrations.AddField(
            model_name='datasubjectrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to='tenants.tenantuser'),
        ),
        migrations.AddField(
            model_name='datasubjectrequest',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_subject_requests', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='databreach',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_breaches', to='tenants.tenantuser'),
        ),
        migrations.AddField(
            model_name='databreach',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_breaches', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='consentrecord',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consent_records', to='tenants.tenantuser'),
        ),
        migrations.AddField(
            model_name='consentrecord',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_records', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='compliancereport',
            name='generated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to='tenants.tenantuser'),
        ),
        migrations.AddField(
            model_name='compliancereport',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_reports', to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='ndprauditlog',
            index=models.Index(fields=['tenant', 'action', '-created_at'], name='ndpr_ndprau_tenant__431aa6_idx'),
        ),
        migrations.AddIndex(
            model_name='ndprauditlog',
            index=models.Index(fields=['tenant', 'user', '-created_at'], name='ndpr_ndprau_tenant__e3be80_idx'),
        ),
        migrations.AddIndex(
            model_name='datasubjectrequest',
            index=models.Index(fields=['tenant', 'request_type', 'status'], name='ndpr_datasu_tenant__58a47b_idx'),
        ),
        migrations.AddIndex(
            model_name='datasubjectrequest',
            index=models.Index(fields=['tenant', 'status', '-submitted_at'], name='ndpr_datasu_tenant__cb9c7d_idx'),
        ),
        migrations.AddIndex(
            model_name='databreach',
            index=models.Index(fields=['tenant', 'breach_type', '-breach_date'], name='ndpr_databr_tenant__f02bf7_idx'),
        ),
        migrations.AddIndex(
            model_name='databreach',
            index=models.Index(fields=['tenant', 'status', '-breach_date'], name='ndpr_databr_tenant__7963db_idx'),
        ),
        migrations.AddIndex(
            model_name='consentrecord',
            index=models.Index(fields=['tenant', 'patient_id', 'status'], name='ndpr_consen_tenant__3fe41a_idx'),
        ),
        migrations.AddIndex(
            model_name='consentrecord',
            index=models.Index(fields=['tenant', 'consent_type', 'status'], name='ndpr_consen_tenant__f7ba5a_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancereport',
            index=models.Index(fields=['tenant', 'report_type', '-period_end'], name='ndpr_compli_tenant__b75ce7_idx'),
        ),
    ]
