# Generated by Django 4.2.7 on 2026-01-31 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='state',
            field=models.CharField(default='Rivers', max_length=100),
        ),
    ]
