# Generated by Django 4.2.19 on 2026-08-02 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_bulkpatientupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='mrn',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=50, null=True, unique=True, verbose_name='Medical Record Number'),
        ),
    ]
