# Generated by Django 4.2.19 on 2026-08-02 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patient_mrn'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='dnr_order',
            field=models.BooleanField(default=False, verbose_name='Do Not Resuscitate'),
        ),
        migrations.AddField(
            model_name='patient',
            name='dnr_order_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='dnr_order_reason',
            field=models.TextField(blank=True),
        ),
    ]
