# Generated by Django 4.2.19 on 2026-08-28 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patient_mpi'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='patient',
            new_name='patients_pa_tenant__dd8881_idx',
            old_name='patients_pa_tenant__a6a3c7_idx',
        ),
        migrations.RenameIndex(
            model_name='patientmerge',
            new_name='patients_pa_tenant__26ed3e_idx',
            old_name='patients_pa_tenant__0e1c23_idx',
        ),
        migrations.RenameIndex(
            model_name='patientmerge',
            new_name='patients_pa_survivo_0f147d_idx',
            old_name='patients_pa_survivo_5ce8b4_idx',
        ),
    ]
