# Generated by Django 4.2.19 on 2026-08-14 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patient_patients_pa_phone_fc49bb_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientvisit',
            name='admission_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientvisit',
            name='disposition_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patientvisit',
            name='disposition_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='patientvisit',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientvisit',
            name='follow_up_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patientvisit',
            name='follow_up_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
