# Generated by Django 4.2.7 on 2026-06-20 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_alter_patient_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='login_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='password',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
